name: lint and test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # update pip; install some static requirements; install all project requirements;
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-xprocess
          pip install git+https://github.com/koi-learning/koi-core
          pip install -e .
      - name: Lint with flake8
        run: |
          # lint the code using flake8;
          flake8 . --count --max-line-length=127 --show-source --statistics
      - name: Test with pytest
        run: |
          pytest